name: 'Android Builder'
on:  push
jobs:
  build-android-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        android_compile_sdk: 36
        android_build_tools: 36.0.0
        android_sdk_tools: 14742923
      with:
        name: javavirys/android:${{ env.android_compile_sdk }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: android_compile_sdk,android_build_tools,android_sdk_tools
